<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LGDN14666-W10" ignored="0" name="Selenium_level1" tests="13" failures="2" timestamp="2021-02-01T14:38:49 ICT" time="184.174" errors="0">
  <testcase name="TC01" time="2.893" classname="railway.TC01_LoginWithValidAccount"/>
  <testcase name="TC02" time="2.134" classname="railway.TC02_LoginWithBlankUsername"/>
  <testcase name="TC03" time="2.209" classname="railway.TC03_LoginWithInvalidPassword"/>
  <testcase name="TC04" time="1.183" classname="railway.TC04_ContactEmailContainsCorrectHref"/>
  <testcase name="TC05" time="5.711" classname="railway.TC05_LoginSeveralTimeWithWrongPassword">
    <failure type="java.lang.AssertionError" message="expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]">
      <![CDATA[java.lang.AssertionError: expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at railway.TC05_LoginSeveralTimeWithWrongPassword.TC05(TC05_LoginSeveralTimeWithWrongPassword.java:27)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC05 -->
  <testcase name="TC06" time="2.716" classname="railway.TC06_AdditionalPagesDisplayAfterLogin"/>
  <testcase name="TC07" time="2.892" classname="railway.TC07_CreateAcountWithValidData"/>
  <testcase name="TC08" time="5.335" classname="railway.TC08_LoginWithAnUnactivedAccount">
    <failure type="java.lang.AssertionError" message="Error message is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message is not displayed expected [true] but found [false]
at railway.TC08_LoginWithAnUnactivedAccount.TC08(TC08_LoginWithAnUnactivedAccount.java:34)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC08 -->
  <testcase name="TC10" time="2.878" classname="railway.TC10_ResetPasswordWithIncorrectEmail"/>
  <testcase name="TC11" time="2.595" classname="railway.TC11_CreateAcountWithBlankPwdAndPID"/>
  <testcase name="TC14" time="10.796" classname="railway.TC14_BookMore10Ticket"/>
  <testcase name="TC15" time="5.455" classname="railway.TC15_GotoBookTicketPageFromTicketPricePage"/>
  <testcase name="TC16" time="8.312" classname="railway.TC16_CancelTicket"/>
</testsuite> <!-- Selenium_level1 -->
